extends Resource

export var settings = [
	["Audio"],
	["Music Volume", 40],
	["Audio Volume", 60],
	["Graphics"],
	["Graphics Quality", 0],
	["Vsync", false],
	["Fullscreen", true],
	["HUD Opacity", 255],
	["HUD Padding", 4],
	["Crosshair", 0],
	["Crosshair Size", 3],
	["Crosshair Outline Size", 3],
	["Colorblind Mode", false],
	["Effects"],
	["Screenshake", false],
	["Screenshake Amount", 30],
	["Particle Amount", 100],
	["Bloom Intensity", 50],
	["Outline Strength", 80],
	["Gameplay"],
	["Always Reload", false],
	["Camera Aim", false],
	["Mouse Sensitivity", 100],
	["Invert Y Axis", false],
	["Show Run Time", false],
	["Autoaim", false],
	["Autoaim Strength", 40],
	["Dash Sensitivity", 50],
	["Input Buffer Time", 15],
	["Damage Numbers", false],
	["Quick Restart Confirmation", true],
	["Miscellanous"],
	["Dropdown_test", 2],
	["Streamer Mode", false],
	["Meme Announcer", false],
	["Chipmunk Voice Filter", false],
	["Low Health SFX Volume", 100],
	["Hitmarker Sound Volume", 100],
	["Weapon Bobbing", true],
	["Weapon Trail Opacity", 100],
	["Extra Enemy Gibs", true],
	["Debug Damage Numbers", false],
	["Cheat Mode", false],


]

var settings_ui = {
	"fgh": "",
	"S_music_volume": [0,100],
	"S_audio_volume": [0,100],
	"fagh": "",
	"S_graphics_quality": [0,4],
	"B_vsync": false,
	"B_fullscreen": true,
	"S_hud_opacity": [0,255],
	"S_hud_padding": [0,150],
	"S_Crosshair": [0,10],
	"S_Crosshair_size": [0,10],
	"S_Crosshair_outline_size": [0,10],
	"B_colorblind_mode": false,
	"tgfd":"",
	"B_screenshake": true,
	"S_screenshake_amount": [0,100],
	"S_particle_amount": [0,200],
	"S_bloom_intensity": [0,100],
	"S_outline_strength": [0,200],
	"wrty": "",
	"B_always_reload": false,
	"B_camera_aim": true,
	"S_mouse_sensitivity": [10,200],
	"B_invert_y_axis": false,
	"B_show_run_time": false,
	"B_autoaim": false,
	"S_autoaim_strength": [0,100],
	"S_dash_sensitivity": [0,100],
	"S_input_buffer_time": [0,60],
	"B_damage_numbers": false,
	"B_quick_restart_confirmation": true,
	"aer": "",
	"D_Dropdown_Test": ["Test 1", "Test 2", "Test 3", "Test 4", "Test 5","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG","TESSGSG"],
	"B_streamer_mode": false,
	"B_meme_announcer": false,
	"B_chipmunk_voice_filter": false,
	"S_low_health_sfx_volume": [0,100],
	"S_hitmarker_sound_volume": [0,100],
	"B_weapon_bobbing": true,
	"S_weapon_trail_opacity": [0,100],
	"B_extra_enemy_gibs": true,
	"B_debug_damage_numbers": false,
	"B_cheat_mode": false,
}

#export var settings = [
#	["Music Volume", 100],
#	["Audio Volume", 100],
#	["Graphics Quality", 0],
#	["Vsync", false],
#	["Fullscreen", true],
#	["Always Reload", false],
#	["HUD Padding", 4],
#	["HUD Opacity", 100],
#	["Camera Aim", false],
#	["Screenshake", false],
#	["Screenshake Amount", 30],
#	["Show Run Time", false],
#	["Autoaim", false],
#	["Autoaim Strength", 40],
#	["Cheat Mode", false],
#]
#
#var settings_ui = {
#	"S_music_volume": [0,100],
#	"S_audio_volume": [0,100],
#	"S_graphics_quality": [0,4],
#	"B_vsync": false,
#	"B_fullscreen": true,
#	"B_always_reload": false,
#	"S_hud_padding": [0,150],
#	"S_hud_opacity": [0,100],
#	"B_camera_aim": true,
#	"B_screenshake": true,
#	"S_screenshake_amount": [0,100],
#	"B_show_run_time": false,
#	"B_autoaim": false,
#	"S_autoaim_strength": [0,100],
#	"B_cheat_mode": false
#}

